### PR TITLE
Fix custom field test in test_nautobot_keeper

### PR DESCRIPTION
**Pull request by scetron**
Fixes a test in test_nautobot_keeper. Custom field is present but set to None instead of not being present at all.

### CODE REVIEW

**Review by chadell — APPROVED** [review]
LGTM

**Comment by mzbroch** [comment]
Can You provide specific explanation of this change ?

I don't understand what has changed over time and what is the exact reason of this unittest failing.

**Review by mzbroch — CHANGES_REQUESTED** [review]
@scetron I believe this to be an issue within Nautobot as reported here - https://github.com/nautobot/nautobot/issues/4175

**Comment by scetron** [comment]
Fixed in Nautobot via https://github.com/nautobot/nautobot/pull/4211 @mzbroch

**Pull request closed without merging**
